#!/bin/bash

cd /opt/app/dmaapbc/etc
for action in "$@"
do
case "$action" in
'backup')
	cp log4j.properties log4j.properties.save 2>/dev/null
	cp dmaapbc.properties dmaapbc.properties.save 2>/dev/null
	cp havecert havecert.save 2>/dev/null
	;;
'stop')
	/opt/app/platform/init.d/dmaapbc stop
	;;
'start')
	/opt/app/platform/init.d/dmaapbc start || exit 1
	;;
'config')
	/bin/bash log4j.properties.tmpl >log4j.properties
	/bin/bash dmaapbc.properties.tmpl >dmaapbc.properties
	/bin/bash havecert.tmpl >havecert
	/bin/bash PolicyEngineApi.properties.tmpl > ../config/PolicyEngineApi.properties
	echo "$AFTSWM_ACTION_NEW_VERSION" >VERSION.dmaapbc
	chmod +x havecert
	rm -f /opt/app/platform/rc.d/K90dmaapbc /opt/app/platform/rc.d/S10dmaapbc
	ln -s ../init.d/dmaapbc /opt/app/platform/rc.d/K90dmaapbc
	ln -s ../init.d/dmaapbc /opt/app/platform/rc.d/S10dmaapbc
	;;
'restore')
	cp log4j.properties.save log4j.properties 2>/dev/null
	cp dmaapbc.properties.save dmaapbc.properties 2>/dev/null
	cp havecert.save havecert 2>/dev/null
	;;
'clean')
	rm -f log4j.properties dmaapbc.properties havecert log4j.properties.save dmaapbc.properties.save havecert.save SHUTDOWN redirections.dat VERSION.dmaapbc
	rm -f /opt/app/platform/rc.d/K90dmaapbc /opt/app/platform/rc.d/S10dmaapbc
	;;
*)
	exit 1
	;;
esac
done
exit 0
