#!/bin/bash /opt/app/osaaf/local/org.onap.dmaap-bc.crontab.sh
# Certificate Manager Crontab Loading Script
# Add/Update a Crontab entry, that adds a check on Certificate Manager generated Certificate nightly.
# Generated by Certificate Manager 2019-03-22T15:53:47.001Z
TFILE="/tmp/cmcron$$.temp"
DIR="/opt/app/osaaf/local"
CF="org.onap.dmaap-bc Certificate Check Script"
SCRIPT="/opt/app/osaaf/local/org.onap.dmaap-bc.check.sh"
crontab -l | sed -n "/#### BEGIN $CF/,/END $CF ####/!p" > $TFILE
# Note: Randomize Minutes (0-60) and hours (1-4)
echo "#### BEGIN $CF ####" >> $TFILE
echo "$(( $RANDOM % 60)) $(( $(( $RANDOM % 3 )) + 1 )) * * * /bin/bash $SCRIPT >> $DIR/cronlog 2>&1 " >> $TFILE
echo "#### END $CF ####" >> $TFILE
crontab $TFILE
rm $TFILE
