version: '3.3'
services:
  dbc-pg-primary:
    container_name: dbc-pg
    image: nexus3.onap.org:10001/crunchydata/crunchy-postgres:centos8-13.2-4.6.1
    ports:
      - "5432:5432"
    environment:
      - PGHOST=/tmp
      - PG_MODE=primary
      - MODE=postgres
      - PG_PRIMARY_USER=dmaapbc
      - PG_PRIMARY_PASSWORD=secret
      - PG_DATABASE=dmaap
      - PG_USER=dmaapbc
      - PG_PASSWORD=secret
      - PG_ROOT_PASSWORD=secret
      - PG_PRIMARY_PORT=5432
    networks:
      dockercompose_net:
        aliases:
          - dbc-pg

  dmaap-bc:
    container_name: dmaap-bc
    hostname: dmaap-bc
    image: onap/dmaap/dmaap-bc:latest
    ports:
    - "30241:8080"
    - "30242:8443"
    volumes:
    - ./buscontroller.env:/opt/app/config/conf/buscontroller.env
    - ./dmaapbc.properties:/opt/app/config/conf/dmaapbc.properties
    #- ./cadi_aaf:/opt/app/osaaf/local
    - ./logback.xml:/opt/app/dmaapbc/etc/logback.xml
    networks:
      dockercompose_net:
        aliases:
          - dmaap-bc
    extra_hosts:
      - dmaap-dr-prov:$dmaap_prov_ip
      - message-router:$dmaap_prov_ip
      - dbc-pg:$dbc_pg_ip

networks:
  dockercompose_net:
    external: true
